version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: {codepipeline-ap-southeast-2-364572886347}
        BUILD_ENV: "nonprod"
phases:
    install:
    on failure: ABORT
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
    on failure: ABORT
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes